spring.data.redis.repositories.enabled: false
eureka.client.enabled: false

server:
  port: ${SERVER_PORT:8080}

jwt.secret: ${JWT_SECRET:prod}

# Database configuration flags
# DATABASE_TYPE: h2  # h2 or h2-memory or mysql
# OBJECT_STORAGE_TYPE: db #db or s3-minio or smb

# Common datasource configuration
spring:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLE:false}
      path: /h2-console
      settings:
        webAllowOthers: true
        autostart: true
  boot:
    admin:
      client:
        url: ${ADMIN_CLIENT_URL:url}
        enable: ${ADMIN_CLIENT_ENABLE:false}
        auto-registration: true
        instance:
          name: ${spring.application.name}

# actuator
management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"

# -----------------------------------H2 specific configuration-----------------------------------

# H2_DB: '/etc/${spring.application.name}/db/h2'
# H2_USERNAME: 'sa'
# H2_PASSWORD: 'password'
# H2_CONSOLE_ENABLE: true
# H2_CONSOLE_PATH: '/h2-console'

# -----------------------------------MySQL specific configuration-----------------------------------

# MYSQL_HOST: 'localhost'
# MYSQL_PORT: 3306
# MYSQL_DB: '${spring.application.name}'
# MYSQL_USERNAME: '${spring.application.name}'
# MYSQL_PASSWORD: 'password'
# MYSQL_USE_SSL: 'false'

# -----------------------------------Redis specific configuration-----------------------------------
# REDIS_ENABLED: false
# REDIS_HOST: "localhost"
# REDIS_PORT: 6379
# REDIS_USERNAME: 
# REDIS_PASSWORD: 

# -----------------------------------Object Storage specific configuration-----------------------------------
# SMB_HOST: localhost
# SMB_PORT: 445
# SMB_DOMAIN: domain
# SMB_USERNAME: username
# SMB_PASSWORD: password
# SMB_SHARE_AND_DIR: Business/data

# S3_URL: http://localhost:9768
# S3_USERNAME: username
# S3_PASSWORD: password
# S3_BUCKET: bucket1